export const data = [
  {
    id: 1,
    project: "OOP Programing",
    task: "Coding Payment function",
    description:
      "This is sample description about task of this project This is sample description about task of this project This is sample description about task of this project This is sample description about task of this project.This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 2,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 3,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 4,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/10/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 5,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/10/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 6,
    project: "OOP Programing 6",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 7,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 8,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 9,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 10,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 11,
    project: "OOP Programing 11",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 12,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 13,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 14,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 15,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 16,
    project: "OOP Programing 17",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 17,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 18,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 19,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 20,
    project: "OOP Programing",
    task: "Coding Payment function",
    description: "This is sample description about task of this project",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
];
