export const data = [
  {
    id: 0,
    member: "Moemoe",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 1,
    member: "Moe",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 2,
    member: "Hop",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 3,
    member: "Jordan",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 4,
    member: "Tien",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/10/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 5,
    member: "Pham",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/10/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 6,
    member: "OOP Programing 6",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 7,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 8,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 9,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 10,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 11,
    member: "OOP Programing 11",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 12,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 13,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 14,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 15,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 16,
    member: "OOP Programing 17",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 17,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 18,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 19,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
  {
    id: 20,
    member: "OOP Programing",
    task: "Coding Payment function",
    note: "",
    startDate: "10/03/2024",
    dueDate: "10/17/2024",
    dateFinish: "",
    action: "Working",
  },
];
